---

- name: "Deploy {{ prometheus_custom_targets_path }}/{{ prometheus_custom_targets_filename }} file with targeted host name only"
  template:
    src: custom_targets.j2
    dest: "{{ prometheus_custom_targets_path }}/{{ prometheus_custom_targets_filename }}"
    mode: 0644
    backup: no
  tags: prometheus,template
